In [1]:
import sklearn #
print('Version: ', sklearn.__version__)

Version:  1.6.1


In [2]:
from sklearn import set_config
set_config(display="diagram")

In [4]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

X, y = load_iris(return_X_y=True)

In [5]:
import numpy as np

newer_data = np.array([[5.5, 2.9, 4.0, 1.4]])

In [6]:
# Inspect the data before proceeding
print(type(X)) # Type of variable X
print(type(y)) # Type of variable y

print(len(X)) # Length of the ndarray X
print(len(y)) # Length of the ndarray y

print(X[:5]) # First n elements of ndarray X
print(y[:5]) # First n elements of ndarray y

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
150
150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [7]:
clf = LogisticRegression(random_state=42,max_iter=1000).fit(X, y)

In [8]:
clf.predict(newer_data) # clf.predict(X[:5, :])

array([1])

In [9]:
clf.predict_proba(newer_data) # clf.predict_proba(X[:5, :])

array([[0.03192282, 0.91933332, 0.04874385]])

In [10]:
clf.score(X, y)

0.9733333333333334